
spring:
  profiles:
    active:
      - prod
      - dev
      - qa
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    hikari:
      username:  tacouser
      password:  tacopassword
logging:
  level:
    tacos: WARN